name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check application
        run: node --check server.js

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        run: vercel deploy --prod --yes --token=${{ secrets.eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im1yay00MzAyZWMxYjY3MGY0OGE5OGFkNjFkYWRlNGEyM2JlNyJ9.eyJpc3MiOiJodHRwczovL29pZGMudmVyY2VsLmNvbS9qYXllc2gta2hvbmRzLXByb2plY3RzIiwic3ViIjoib3duZXI6amF5ZXNoLWtob25kcy1wcm9qZWN0czpwcm9qZWN0OmNpLWNkLWFzc2lnbm1lbnQ6ZW52aXJvbm1lbnQ6ZGV2ZWxvcG1lbnQiLCJzY29wZSI6Im93bmVyOmpheWVzaC1raG9uZHMtcHJvamVjdHM6cHJvamVjdDpjaS1jZC1hc3NpZ25tZW50OmVudmlyb25tZW50OmRldmVsb3BtZW50IiwiYXVkIjoiaHR0cHM6Ly92ZXJjZWwuY29tL2pheWVzaC1raG9uZHMtcHJvamVjdHMiLCJvd25lciI6ImpheWVzaC1raG9uZHMtcHJvamVjdHMiLCJvd25lcl9pZCI6InRlYW1fYkVEYzk5djNwVE9RbDc1ZnF2b1BrbnRDIiwicHJvamVjdCI6ImNpLWNkLWFzc2lnbm1lbnQiLCJwcm9qZWN0X2lkIjoicHJqX3Y1ejRKSUlwbVpHQjdOMHFyc21JWmIxb1F5c20iLCJlbnZpcm9ubWVudCI6ImRldmVsb3BtZW50IiwicGxhbiI6ImhvYmJ5IiwidXNlcl9pZCI6ImR3TWE4T1B6OFZuNktuczdjbHlWN1NZMiIsImNsaWVudF9pZCI6ImNsX0hZeU9QQk50Rk1mSGhhVW45TDRRUGZUWno2VFA0N2JwIiwiYXBwX2lkIjoiY2xfSFl5T1BCTnRGTWZIaGFVbjlMNFFQZlRaejZUUDQ3YnAiLCJuYmYiOjE3ODc5Mjc2NzcsImlhdCI6MTc4NzkyNzY3NywiZXhwIjoxNzg3OTcwODc3fQ.a9V9emkfv-Cv-xtHY79ABwpLMXzBaS9pgsMJ2zsmXIWPC3aZ_lSWkvAWYNINx6IjXarlq5iPkvigAtxM5anS1iqm2XUMtNdTT9scgFqk557m1INMaqyntBtuP8mS37QuJtGGsV1PSEsjOWwUG29_XILBDoRSE7yGxeB1jEF-sS7t1CMl8EixAgyygGexfUvizvffh2RfrpCpMv6vSQlkANfmuhSF2-7TcFNKODWcIkId0f7esfr7eVrRTgoa1ADkYX9KeDOn7lyQ5vmXJAfeJ6ZmK4a2hF0kui80A1WryYYToMh52G3CGSo8shXxAA-dmaPGD0brWgT1531IF96Vkg }}
        env:
          VERCEL_ORG_ID: dwMa8OPz8Vn6Kns7clyV7SY2
          VERCEL_PROJECT_ID: prj_v5z4JIIpmZGB7N0qrsmIZb1oQysm